server:
  port: 8080

spring:
  application:
    name: catalogo-produtos
  datasource:
    url: jdbc:postgresql://localhost:5432/catalogo
    username: catalogo
    password: catalogo
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true
  flyway:
    enabled: true
    locations: classpath:db/migration

logging:
  level:
    org.hibernate.SQL: debug
